---
- name: Download nrpe plugin
  get_url:
    url: "{{ nrpe_url }}"
    dest: /root
- name: untar the nagios
  command: tar xvf /root/nrpe-2.15.tar.gz
- name: configure Nrpe
  command: ./configure --enable-command-args --with-nagios-user=nagios --with-nagios-group=nagios --with-ssl=/usr/bin/openssl --with-ssl-lib=/usr/lib/x86_64-linux-gnu
  args:
    chdir: "{{ nagios_nrpe_home }}"
- name: make all the nrpe plugin
  command: make all
  args:
    chdir: "{{ nagios_nrpe_home }}"
- name: sudo make install the nrpe plugin
  make: 
    chdir: "{{ nagios_nrpe_home }}"
    target: install
- name: make all the nrpe plugin
  command: make install-xinetd
  args:
    chdir: "{{ nagios_nrpe_home }}"
- name: make all the nrpe plugin
  command: make install-daemon-config
  args:
    chdir: "{{ nagios_nrpe_home }}"
- name: add the nrpe nagios ip to config file
  replace:
    dest: /etc/xinetd.d/nrpe
    regexp: '127.0.0.1'
    replace: '{{ ip }}'
    backup: yes
- name: restart the xinetd service
  service: name=xinetd state=restarted
- name: Enable client servers folder in nagios config file
  replace:
    dest: /usr/local/nagios/etc/nagios.cfg
    regexp: '#cfg_dir=/usr/local/nagios/etc/servers'
    replace: 'cfg_dir=/usr/local/nagios/etc/servers'
    backup: yes
- name: create servers folder
  file:
    path: /usr/local/nagios/etc/servers
    state: directory
- name: update the nagios email address for notification
  replace:
    dest: /usr/local/nagios/etc/objects/contacts.cfg
    regexp: 'nagios@localhost'
    replace: '{{ email }}'
    backup: yes
- name: adding nrpe command to commands list
  template:
    src: commands.j2
    dest: /usr/local/nagios/etc/objects/commands.cfg
    owner: nagios
    group: nagios
    mode: 0644
- name: install apache rewrite
  command: a2enmod rewrite
- name: enable cgi
  command: a2enmod cgi
#- name: create nagiosadmin password
#  shell: htpasswd -cb /etc/nagios/passwd nagiosadmin { password }}
- name: create a link file for nagios confgi file
  file:
    src: /etc/apache2/sites-available/nagios.conf
    dest: /etc/apache2/sites-enabled/
    state: link
  notify:
   - start the nagios
   - start the apache   
- name: nagios config file
  template:
    src: nagios.j2
    dest: /etc/apache2/sites-available/nagios.conf
    owner: root
    group: root
    mode: 0644
  notify:
   - start the nagios
   - start the apache
